config:
  namespace: Game

AudioSettings @not_a_component @json_with_keys:
  masterVolume: [ float, 1. ]

GraphicsSettings @not_a_component @json_with_keys:

  imGuiFont: [string, "assets/fonts/ruda/Ruda-Bold.ttf"]

  gammaCorrection: [float, 1.3]
  msaaSamples: [uint8, 0]
  bloomBlurIterations: [uint8, 0]
  bloomThreshold: [float, 8]
  shadows: [bool, true]
  maxArmatureBones: [uint, 64]
  fogStart: [float, 180]
  fogEnd: [float, 800]
  fogEnabled: [bool, true]

  prefilteredReflectionMapResolution: [uint, 256]
  prefilteredReflectionMapSamples: [uint, 2048]
  convolutionStepDelta: [float, 0.02]
  
  uiPixelScaling: [uint, 3]

  debugShadowBoxes: [bool, true]
  debugArmatures: [bool, true]
  debugColliders: [bool, false]
  debugGravityFieldAffected: [bool, false]
  debugColliderAABBs: [bool, false]
  debugConstraints: [bool, false]
  debugConstraintLimits: [bool, false]

KeyInputSettings @not_a_component @json_with_keys:

  walkForwards: [KeyInput::Key, GLFW_KEY_W]
  walkLeft: [KeyInput::Key, GLFW_KEY_A]
  walkBackwards: [KeyInput::Key, GLFW_KEY_S]
  walkRight: [KeyInput::Key, GLFW_KEY_D]
  jump: [KeyInput::Key, GLFW_KEY_SPACE]

  meal: [KeyInput::Key, GLFW_KEY_E]

  flyCamera: [KeyInput::Key, GLFW_KEY_F9]
  retryLevel: [KeyInput::Key, GLFW_KEY_F10]
  stopFlyingCamera: [KeyInput::Key, GLFW_KEY_ESCAPE]

  moveEntity: [KeyInput::Key, GLFW_KEY_G]
  gizmoNeedCtrl: [bool, true]
  gizmoToggleLocal: [KeyInput::Key, GLFW_KEY_L]
  gizmoTranslate: [KeyInput::Key, GLFW_KEY_T]
  gizmoRotate: [KeyInput::Key, GLFW_KEY_R]
  gizmoScale: [KeyInput::Key, GLFW_KEY_S]

GamepadInputSettings @not_a_component @json_with_keys:
  walkX: [GamepadInput::Axis, GLFW_GAMEPAD_AXIS_LEFT_X]
  walkY: [GamepadInput::Axis, GLFW_GAMEPAD_AXIS_LEFT_Y]
  jump: [GamepadInput::Button, GLFW_GAMEPAD_BUTTON_A]

  test: [GamepadInput::Button, GLFW_GAMEPAD_BUTTON_B]

Settings @not_a_component @json_with_keys:

  graphics: GraphicsSettings
  audio: AudioSettings
  keyInput: KeyInputSettings
  gamepadInput: GamepadInputSettings
  customSettings: [ json, json::object() ]
  limitUpdatesPerSec: [ bool, false ]
  showDeveloperOptions: [ bool, false ]

